/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.travelab.gateway;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class ServiceGatewayApplication {

	@Bean
	public RouteLocator myRoutes(RouteLocatorBuilder builder) {
		return builder
			.routes()
			.route(p -> p
				.path("/reservation")
				.uri("http://localhost:8080"))
			.route(p -> p
				.path("/checkin")
				.uri("http://localhost:8080"))
			.build();
	}
}
